### ISSUE TITLE
Incorrect Error Reported on SecurityGroupIngress

### ISSUE THREAD

**Issue by ialford** [awslabs/aws-cfn-lint-atom#19]
On both the [CloudFormation Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html#aws-properties-ec2-security-group-ingress-examples) page and in our environment, using single quotes around the FromPort and ToPort values in YAML templates is both accepted and works as expected. However, the linter provides the following:

![image](https://user-images.githubusercontent.com/25667219/50692084-b1c47f00-1000-11e9-9dd4-1c6f0266cfbd.png)

I am wondering if this should be reported as a warning that the quotes aren't a requirement rather than an error, as the CloudFormation will run and the groups will work as expected when the integer value is quoted in YAML.

atom-cfn-lint version 0.6.2 and cfn-lint version 0.10.2

**Comment by kddejong** [comment]
I'm going to close this one in favor of the following few issues.  The short answer is we rely on the CloudFormation spec published here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html.  While in most cases CloudFormation will convert types between different types we have found scenarios that it doesn't.  Since there is nothing in the spec to say if the type checking is strict we have had to make it strict.  

You can follow the following issues for more information:
https://github.com/awslabs/cfn-python-lint/issues/547
https://github.com/awslabs/cfn-python-lint/issues/42
