### ISSUE TITLE
Invalid Property Resources

### ISSUE THREAD

**Issue by acbrazie** [awslabs/aws-cfn-lint-atom#26]
2 False Positives for "Invalid Property Resources":

Error	Invalid Property Resources/Route/Properties/TransitGatewayId
Resource supported - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-route.html

Error	Invalid Property Resources/Instance/Properties/BlockDeviceMappings/0/Ebs/KmsKeyId
Resource supported - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-blockdev-template.html

**Comment by kddejong** [comment]
What version of `cfn-lint` are using?

**Comment by acbrazie** [comment]
0.7.0

**Comment by kddejong** [comment]
Sorry, this is a little tricky since the Atom plugin calls an executable that is installed seperately.  

The version of the atom plugin is probably 0.7.0. That plugin calls `cfn-lint` which is installed separately.  https://github.com/aws-cloudformation/cfn-python-lint

Typically this issue can be resolved by upgrade the python package `cfn-lint` or by running `cfn-lint --update-specs`

**Comment by acbrazie** [comment]
Thanks kddejong, updating cfn-python-lint did the trick.
